[package]
org = "happy-wakey"
name = "happy-wakey-web-server"
version = "0.1.0"
description = "MASH, Leptos, and Dioxus Happy Wakey web servers"

[package.repository]
vcs = "git"
url = "https://github.com/happy-wakey/happy-wakey-web-server.rs"

[dependencies]
"happy-wakey/happy-wakey-orm-core" = "^0.1.0"
"happy-wakey/happy-wakey-interfaces" = "^0.1.0"
"happy-wakey/happy-wakey-lib-core" = "^0.1.0"
"opto-sync/syncer-rs" = "^0.3.0"
"oresoftware/next-loggers-rust" = "^0.1.0"

[targets.mash]
dir = "frontends/mash"
adapter = "rust"
[targets.leptos]
dir = "frontends/leptos"
adapter = "rust"
[targets.dioxus]
dir = "frontends/dioxus"
adapter = "rust"