[workspace]
members = ["crates/common", "frontends/mash", "frontends/leptos", "frontends/dioxus"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/happy-wakey/happy-wakey-web-server.rs"

[workspace.dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["macros"] }
happy-wakey-web-common = { path = "crates/common" }
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tower-http = { version = "0.6", features = ["set-header", "trace"] }
