[package]
name = "happy-wakey-web-common"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-nats = { version = "0.50", default-features = false, features = ["jetstream", "nkeys", "ring", "server_2_10"] }
axum.workspace = true
bytes = "1"
futures-util = "0.3"
happy-wakey-interfaces = { git = "https://github.com/happy-wakey/happy-wakey-interfaces.git", rev = "d6278ec8f6b2263678728b147a32dff92d52d8c8" }
happy-wakey-lib-core = { git = "https://github.com/happy-wakey/happy-wakey-lib-core.git", rev = "9638429097bc68b2aac280d4e3edaa92db96f85a", default-features = false, features = ["read-only"] }
next-loggers = { package = "oresoftware-next-loggers", git = "https://github.com/ores-otel/ores.otel.log.git", rev = "ca176fb6768a9750d262a536952268625ffd3a8a" }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
rustls-pemfile = "2"
serde.workspace = true
serde_json.workspace = true
syncer-rs = { git = "https://github.com/opto-sync/syncer.rs.git", rev = "f8dfef90722dc423d442388f61856958a177d36f" }
tokio.workspace = true
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
uuid = { version = "1", features = ["v4"] }
