[package]
name = "happy-wakey-mash"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
k8s-web-api-data-plane = { git = "https://github.com/ORESoftware/k8s-libs-and-shared-defs.git", rev = "55adadc9f6d223d40b28ae66097dfe16930951b1", package = "k8s-web-api-data-plane" }
anyhow.workspace = true
axum.workspace = true
happy-wakey-web-common.workspace = true
maud = { version = "0.27", features = ["axum"] }
tokio.workspace = true
tower-http.workspace = true

